name: "Firewall Rule Removal Request"
description: "Remove one existing firewall rule. For multiple removals, open this form multiple times."
labels:
  - "firewall-change-request"

body:
  - type: input
    id: reqid
    attributes:
      label: "Request ID (REQID)"
      placeholder: "REQ12345"
      description: "Your request identifier (REQ followed by digits)"
    validations:
      required: true

  - type: input
    id: carid
    attributes:
      label: "CARID"
      placeholder: "APP1"
      description: "Your team or application identifier"
    validations:
      required: true

  - type: input
    id: existing_rule_name
    attributes:
      label: "Rule Name to Remove"
      placeholder: "AUTO-APP1-REQ12345-1-TCP-443"
      description: "The exact name of the rule to delete"
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: "Business Justification for Removal"
      description: "Why should this rule be removed?"
    validations:
      required: true
