name: "Firewall Rule Update/Removal Request"
description: "Update or remove existing firewall rules via structured JSON input."
labels:
  - "firewall-update-request"

body:
  - type: input
    id: reqid
    attributes:
      label: "Request ID (REQID)"
      placeholder: "REQ12345"
      description: "Your request identifier (REQ followed by digits)"
    validations:
      required: true

  - type: input
    id: carid
    attributes:
      label: "CARID"
      placeholder: "APP1"
      description: "Your team or application ID"
    validations:
      required: true

  - type: textarea
    id: rules_json
    attributes:
      label: "Rules JSON"
      description: |
        Paste a JSON array of rule objects. Each object must include:
        - **action**: `"update"` or `"remove"`
        - **existing_rule_name**: string, e.g. `"AUTO-APP1-REQ12345-1-TCP-443"`
        - If `action=="update"`, also:
          - **new_source_ips**, **new_destination_ips**, **new_ports**,  
            **new_protocol**, **new_direction**, **new_justification**
    validations:
      required: true
      pattern: "^\\[.*\\]$"
      pattern_error: "Must be a JSON array (e.g. `[ {...}, {...} ]`)."
