name: Firewall Rule Request
description: Request one or more GCP network firewall rules
labels:
  - firewall-request
body:
  - type: input
    id: request_id
    attributes:
      label: Request ID (REQID)
      description: Unique per request, e.g. REQ12345
      placeholder: REQ12345

  - type: textarea
    id: business_justification
    attributes:
      label: Overall Business Justification
      description: High-level justification for this firewall change

  - type: textarea
    id: rules
    attributes:
      label: Rules
      description: |
        Enter one or more rules in the following format (copy for each rule):

        ```
        Source: 203.0.113.25/32
        Destination: 10.1.2.0/24
        Ports: 443,8443
        Protocol: TCP
        Direction: INGRESS
        Justification: Needed for XYZ service
        ```
      placeholder: |
        Source: 203.0.113.25/32
        Destination: 10.1.2.0/24
        Ports: 443,8443
        Protocol: TCP
        Direction: INGRESS
        Justification: Needed for XYZ service
