name: "Firewall Rule Update/Removal Request"
description: "Submit update or removal for one or more existing firewall rules as JSON."
labels:
  - "firewall-update-request"

body:
  - type: input
    id: reqid
    attributes:
      label: "Request ID (REQID)"
      description: "REQ#### format"
    validations:
      required: true

  - type: input
    id: carid
    attributes:
      label: "CARID"
      description: "Your team or application ID"
    validations:
      required: true

  - type: textarea
    id: rules_json
    attributes:
      label: "Rules JSON"
      description: |
        Paste a JSON array of rule‐objects.  
        Each object must have:
        - `action`: `"update"` or `"remove"`  
        - `existing_rule_name`: string  
        - If `"update"`:
          - `new_source_ips`, `new_destination_ips`, `new_ports`, 
            `new_protocol`, `new_direction`, `new_justification`
    validations:
      required: true
      pattern: "\\[.*\\]"    # simple “must start/end with [ ]”
      pattern_error: "Must be a JSON array (e.g. [ {...}, {...} ])"
