name: "Firewall Rule Update Request"
description: "Update one existing firewall rule. For multiple updates, open this form multiple times."
labels:
  - "firewall-change-request"

body:
  - type: input
    id: reqid
    attributes:
      label: "Request ID (REQID)"
      placeholder: "REQ12345"
      description: "Your request identifier (REQ followed by digits)"
    validations:
      required: true

  - type: input
    id: carid
    attributes:
      label: "CARID"
      placeholder: "APP1"
      description: "Your team or application identifier"
    validations:
      required: true

  - type: input
    id: existing_rule_name
    attributes:
      label: "Existing Rule Name"
      placeholder: "AUTO-APP1-REQ12345-1-TCP-443"
      description: "The exact name of the rule to update"
    validations:
      required: true

  - type: input
    id: new_source_ips
    attributes:
      label: "New Source IP(s) or CIDR(s)"
      placeholder: "203.0.113.55/32"
      description: "e.g. single IP or CIDR; comma-separated for lists"
    validations:
      required: true

  - type: input
    id: new_destination_ips
    attributes:
      label: "New Destination IP(s) or CIDR(s)"
      placeholder: "10.1.2.22/32"
    validations:
      required: true

  - type: input
    id: new_ports
    attributes:
      label: "New Port(s)"
      placeholder: "443"
      description: "Single port (443), list (80,443), or range (1000-2000)"
    validations:
      required: true

  - type: dropdown
    id: new_protocol
    attributes:
      label: "New Protocol"
      options:
        - tcp
        - udp
        - icmp
      description: "Select protocol"
    validations:
      required: true

  - type: dropdown
    id: new_direction
    attributes:
      label: "New Direction"
      options:
        - INGRESS
        - EGRESS
      description: "Traffic direction"
    validations:
      required: true

  - type: textarea
    id: new_justification
    attributes:
      label: "Business Justification"
      description: "Why is this change needed?"
    validations:
      required: true
