name: 🤝 Auto-merge on PR approval

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Must be one line inside ${{ … }}
    if: ${{ github.event.review.state == 'approved' && contains(github.event.pull_request.labels.*.name, 'pending-review') && startsWith(github.event.pull_request.head.ref, 'firewall-req-') }}
    steps:
      - name: Merge the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash',
            });
